# Generated by Django 4.0.2 on 2022-03-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mobiles', 'Mobiles'), ('Laptop', 'Laptop'), ('TopWear', 'TopWear'), ('BottomWear', 'BottomWear')], max_length=20),
        ),
    ]
