# Generated by Django 4.0.2 on 2022-03-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_contact_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='person',
            field=models.CharField(choices=[('Mr Roopesh Rai', 'Mr Roopesh Rai'), ('Mr Om Ahuja', 'Mr Om Ahuja'), ('Mr Anand Tank', 'Mr Anand Tank')], max_length=50),
        ),
    ]
