# Generated by Django 4.0.2 on 2022-03-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_contact_email_alter_contact_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='person',
            field=models.CharField(max_length=50),
        ),
    ]
