# Generated by Django 4.0.2 on 2022-03-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_product_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactform',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('person', models.CharField(max_length=50)),
                ('context', models.TextField()),
            ],
        ),
    ]
