# Generated by Django 4.0.2 on 2022-03-14 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_contactform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contactform',
            new_name='checkoutform',
        ),
    ]
