# Generated by Django 4.0.2 on 2022-03-14 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_checkoutform_amount_checkoutform_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutform',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='checkoutform',
            name='product',
        ),
        migrations.RemoveField(
            model_name='checkoutform',
            name='user',
        ),
    ]
