# Generated by Django 4.0.2 on 2022-03-15 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_checkoutform_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutform',
            name='amount',
        ),
    ]
