# Generated by Django 4.0.2 on 2022-03-17 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_checkoutform_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
