# Generated by Django 4.0.2 on 2022-03-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_product_stripe_product_id_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_price_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
