# Generated by Django 4.0.2 on 2022-03-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_product_stripe_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
