# Generated by Django 4.0.3 on 2022-03-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file',
            field=models.FileField(default=1, upload_to='product_files/'),
            preserve_default=False,
        ),
    ]
