# Generated by Django 4.0.3 on 2022-04-26 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
