# Generated by Django 4.0.3 on 2022-04-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_product_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(default=1, upload_to='productimg'),
            preserve_default=False,
        ),
    ]
